data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-retail-big-data'
    dataset: retail
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: d17fe4d2-dc8f-442b-8a77-32ede3c99863
  api_key_secret: RH6cfjnlJbGog6oewM50YzKqCrCL9-NwsgQ9Hmz0bYpTjpI_QETr9g